### ISSUE TITLE
The interface doesn't show with tunnelmon -c

### ISSUE THREAD

**Issue by DavideGSpotview** [nojhan/tunnelmon#7]
**Describe the bug**
WARNING:root:It's a bad idea to log to stdout while in the curses interface.

**To Reproduce**
1. Execute tunnelmon from the command line with the -c option: tunnelmon -c

**Expected behavior**
To show an interactive interface

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 22.04.1 LTS

**Comment by nojhan** [comment]
Can you indicate your Python version?
I've got an Ubuntu jammy as well here, and it works just fine with Python 3.10.6.

**Comment by DavideGSpotview** [comment]
The python version is 3.10

**Comment by nojhan** [comment]
Can you upload here the content of the `tunnelmon.log` file after having done `python3 tunnelmon.py -c --log-level debug --log-file tunnelmon.log`?

**Comment by DavideGSpotview** [comment]
I can't for security reasons sorry. It gives me this additional response:
Traceback (most recent call last):
  File "/usr/bin/tunnelmon", line 794, in <module>
    mc()
  File "/usr/bin/tunnelmon", line 490, in __call__
    self.display()
  File "/usr/bin/tunnelmon", line 542, in display
    header_msg = " ".join(self.format()).format(*self.header)
IndexError: Replacement index 7 out of range for positional args tuple

**Comment by nojhan** [comment]
I just committed 2d95669928a3c3aca948690b3cb6c3e016d216cb, so that you may have logs without sensitive information. Just update your repository and rerun the command (sensitive information will not be logged anymore, unless you pass `--log-sensitive`).
